---
name: Docker Image CI
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
    paths:
      - 'build/package/Dockerfile'
  pull_request:
    branches: ["main"]
    paths:
      - 'build/package/Dockerfile'

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./build/package/Dockerfile
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          file: build/package/Dockerfile
