# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: [ "main" ]
    paths:
    - '**/*.go'
    - 'go.mod'
    - 'go.sum'
    - 'config/config.example.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
    - '**/*.go'
    - 'go.mod'
    - 'go.sum'
    - 'config/config.example.yaml'

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test with Go
      run: go test -v ./...
      
  golangci:
    name: GoLangCI-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
  
  yamlLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
